"""CET-6 常见短语词典（两词及以上的多词短语）"""

CET6_PHRASES = {
    # A
    "a great many", "a large amount of", "a number of", "a series of",
    "a variety of", "abide by", "account for", "accuse of", "act on",
    "adapt to", "add to", "adjust to", "agree on", "agree to",
    "aim at", "allow for", "amount to", "appeal to", "apply for",
    "apply to", "approve of", "argue about", "arrive at", "ask for",
    "associate with", "attach to", "attempt to", "attend to",
    "attribute to",
    # B
    "back up", "base on", "because of", "begin with", "believe in",
    "belong to", "benefit from", "blame for", "blame on", "break down",
    "break in", "break into", "break off", "break out", "break through",
    "break up", "bring about", "bring forward", "bring in", "bring up",
    "build up", "burn out", "burst into",
    # C
    "call for", "call off", "call on", "call up", "calm down",
    "campaign for", "can not help", "care about", "care for",
    "carry on", "carry out", "cast aside", "catch fire", "catch up with",
    "cater to", "check in", "check out", "check up on", "cheer up",
    "clear away", "clear up", "cling to", "close to", "come about",
    "come across", "come along", "come back", "come by", "come down",
    "come from", "come into being", "come into effect",
    "come into use", "come off", "come on", "come out",
    "come to", "come to an end", "come to the point", "come true",
    "come up", "come up with", "comment on", "commit to",
    "compare to", "compare with", "compensate for", "compete with",
    "complain about", "comply with", "concentrate on", "confess to",
    "confide in", "confine to", "conform to", "confront with",
    "connect with", "consent to", "consist of", "contribute to",
    "cope with", "correspond to", "count on", "cover up",
    "crack down on", "crash into", "cross out", "cure of",
    "cut across", "cut back", "cut down", "cut in", "cut off",
    "cut out", "cut short",
    # D
    "deal in", "deal with", "decide on", "dedicate to", "derive from",
    "devote to", "die down", "die out", "differ from", "differ in",
    "dig into", "dip into", "disagree with", "discriminate against",
    "distinguish from", "divide into", "do away with", "do without",
    "draw attention", "draw back", "draw in", "draw up", "dress up",
    "drop by", "drop in", "drop out", "dry up", "dwell on",
    # E
    "engage in", "equip with", "even if", "even though", "ever since",
    "every now and then", "every other", "except for", "excuse from",
    "exert on", "expose to",
    # F
    "face to face", "face up to", "fall apart", "fall back on",
    "fall behind", "fall in love with", "fall into", "fall off",
    "fall out", "fall over", "far from", "feed on", "figure out",
    "fill in", "fill out", "fill up", "find fault with", "find out",
    "first of all", "fit in", "focus on", "follow up", "fond of",
    "for ever", "for example", "for instance", "for the sake of",
    "for the time being", "free from", "free of charge",
    "freeze up", "frown on", "furnish with",
    # G
    "get across", "get along with", "get around", "get away",
    "get away with", "get back", "get by", "get down to",
    "get hold of", "get in", "get in the way", "get into",
    "get off", "get on", "get on with", "get out", "get out of",
    "get over", "get rid of", "get through", "get together",
    "get up", "give away", "give back", "give in", "give off",
    "give out", "give rise to", "give up", "give way to",
    "glance at", "go after", "go against", "go ahead", "go along with",
    "go around", "go back on", "go beyond", "go by", "go down",
    "go for", "go in for", "go into", "go off", "go on",
    "go out", "go out of", "go over", "go through", "go with",
    "go without", "go wrong", "grow up", "guard against",
    # H
    "hand down", "hand in", "hand in hand", "hand out", "hand over",
    "hang about", "hang on", "hang up", "happen to", "hardly any",
    "hardly ever", "have access to", "have nothing to do with",
    "have to do with", "head for", "hear from", "hear of",
    "heart and soul", "help oneself to", "hide from", "hold back",
    "hold on", "hold onto", "hold out", "hold up", "how about",
    "hunt for", "hurry up",
    # I
    "identify with", "if only", "impose on", "improve on",
    "in a hurry", "in a sense", "in a way", "in a word",
    "in accordance with", "in addition", "in addition to",
    "in advance", "in all", "in any case", "in brief",
    "in case", "in case of", "in charge of", "in common",
    "in comparison with", "in consequence", "in contrast",
    "in contrast to", "in control of", "in danger", "in debt",
    "in detail", "in difficulty", "in effect", "in essence",
    "in excess of", "in exchange for", "in fact", "in favor of",
    "in force", "in front of", "in general", "in hand",
    "in honor of", "in itself", "in light of", "in line with",
    "in memory of", "in no case", "in no time", "in one's opinion",
    "in order", "in order to", "in other words", "in part",
    "in particular", "in person", "in place of", "in practice",
    "in proportion to", "in public", "in quantity", "in question",
    "in reality", "in regard to", "in relation to", "in return",
    "in search of", "in sight", "in spite of", "in support of",
    "in terms of", "in the course of", "in the end",
    "in the event of", "in the face of", "in the first place",
    "in the future", "in the habit of", "in the interests of",
    "in the light of", "in the long run", "in the meantime",
    "in the middle of", "in the past", "in the way", "in theory",
    "in time", "in touch", "in turn", "in vain", "in view of",
    "incline to", "indulge in", "inform of", "innocent of",
    "insist on", "interfere in", "interfere with", "invest in",
    "invite to", "involve in",
    # J
    "join in", "join up", "judging by", "jump to conclusion",
    "just about", "just as", "just now",
    # K
    "keep an eye on", "keep back", "keep company with", "keep down",
    "keep from", "keep in mind", "keep in touch with", "keep off",
    "keep on", "keep out of", "keep to", "keep up",
    "keep up with", "knock down", "knock out", "know about",
    # L
    "lack of", "laugh at", "launch into", "lay aside", "lay down",
    "lay off", "lay out", "lead to", "lean on", "learn about",
    "leave alone", "leave behind", "leave out", "lend to",
    "let alone", "let down", "let go", "let in", "let off",
    "let out", "lie in", "light up", "limit to", "line up",
    "link to", "listen to", "little by little", "live by",
    "live on", "live through", "live up to", "long for",
    "look after", "look back", "look down on", "look for",
    "look forward to", "look in", "look into", "look like",
    "look on", "look out", "look out for", "look over",
    "look through", "look to", "look up", "look up to",
    "lose sight of", "lose weight",
    # M
    "major in", "make a difference", "make a face", "make a fuss",
    "make a point", "make an effort", "make for", "make friends with",
    "make fun of", "make it", "make no sense", "make of",
    "make off", "make one's way", "make out", "make progress",
    "make room for", "make sense", "make sure", "make the best of",
    "make the most of", "make up", "make up for", "make up one's mind",
    "make use of", "make way for", "many a", "may as well",
    "mean to", "measure up", "meet with", "mistake for", "mix up",
    "more or less",
    # N
    "name after", "neither here nor there", "never mind",
    "next door", "no doubt", "no less than", "no longer",
    "no matter how", "no matter what", "no more", "no more than",
    "no sooner than", "no wonder", "none other than", "not only",
    "not to mention", "nothing but", "now and then", "now that",
    # O
    "object to", "occur to", "off and on", "on a large scale",
    "on account of", "on average", "on behalf of", "on board",
    "on business", "on condition that", "on demand", "on duty",
    "on earth", "on fire", "on foot", "on guard", "on hand",
    "on one's own", "on purpose", "on sale", "on schedule",
    "on second thoughts", "on the basis of", "on the contrary",
    "on the grounds of", "on the one hand", "on the other hand",
    "on the part of", "on the point of", "on the spot", "on the whole",
    "on time", "on top of", "once again", "once for all",
    "once in a while", "once more", "once upon a time",
    "open to", "operate on", "oppose to", "or else", "or so",
    "originate from", "other than", "ought to", "out of",
    "out of breath", "out of control", "out of danger",
    "out of date", "out of order", "out of place", "out of practice",
    "out of question", "out of the question", "out of touch",
    "over and over again", "owe to", "owing to",
    # P
    "participate in", "pass away", "pass by", "pass on", "pass out",
    "pass through", "pay attention to", "pay back", "pay for",
    "pay off", "persist in", "pick out", "pick up", "pile up",
    "plan for", "play a role in", "play a part in", "play with",
    "plead for", "plenty of", "point at", "point out", "point to",
    "pour into", "prefer to", "prepare for", "preserve from",
    "press for", "prevail over", "prevent from", "pride oneself on",
    "prior to", "provide for", "provide with", "pull down",
    "pull in", "pull off", "pull out", "pull through", "pull up",
    "push aside", "push for", "push forward", "push on",
    "put across", "put aside", "put away", "put down",
    "put forward", "put in", "put into practice", "put off",
    "put on", "put out", "put through", "put to use", "put up",
    "put up with",
    # Q
    "qualified for",
    # R
    "rather than", "reach for", "react against", "react to",
    "read out", "reason with", "recover from", "refer to",
    "refer to as", "reflect on", "refrain from", "regard as",
    "register for", "related to", "relate to", "rely on",
    "remark about", "remedy for", "remind of", "remove from",
    "replace with", "reply to", "report to", "resign from",
    "resist to", "resolve into", "resort to", "respond to",
    "responsible for", "rest on", "restore to", "result from",
    "result in", "rich in", "rid of", "ride out", "right away",
    "ring off", "ring up", "rise up", "rob of", "roll in",
    "roll up", "root in", "round up", "rule out", "run across",
    "run after", "run against", "run away", "run down",
    "run into", "run off", "run out", "run out of", "run over",
    "run through", "run up against",
    # S
    "safe from", "save for", "scale down", "search for",
    "secret from", "secure from", "see about", "see off",
    "see through", "see to", "seek after", "seek for", "seize on",
    "select from", "send for", "send in", "send off", "send out",
    "separate from", "separate into", "serve as", "serve right",
    "set about", "set aside", "set back", "set down", "set fire to",
    "set forth", "set free", "set in", "set off", "set on",
    "set out", "set up", "settle down", "shake off",
    "share with", "shelter from", "shield from", "shoot at",
    "short of", "show off", "show up", "shrug off", "shut down",
    "shut out", "shut up", "side by side", "side with",
    "sign in", "sign up", "single out", "sit for", "sit in",
    "sit up", "size up", "slow down", "smell of", "smooth over",
    "so as to", "so far", "so that", "something of",
    "sooner or later", "sort out", "speak about", "speak highly of",
    "speak of", "speak out", "specialize in", "speed up",
    "spread out", "spring up", "stand by", "stand for",
    "stand out", "stand up", "stand up for", "stand up to",
    "stare at", "start off", "start up", "stay away from",
    "stay up", "step by step", "step in", "step up",
    "stick out", "stick to", "stir up", "stop from",
    "store up", "straight away", "strange to", "stretch out",
    "strip of", "struggle against", "subject to", "submit to",
    "substitute for", "succeed in", "suffer from", "sum up",
    "summon up", "supply with", "sure enough", "surprise at",
    "suspect of", "switch off", "switch on", "sympathize with",
    # T
    "take a break", "take a look", "take action", "take advantage of",
    "take after", "take apart", "take away", "take back",
    "take care", "take care of", "take charge of", "take delight in",
    "take down", "take effect", "take for", "take for granted",
    "take in", "take into account", "take into consideration",
    "take it easy", "take note of", "take notice of", "take off",
    "take on", "take one's time", "take out", "take over",
    "take pains", "take part in", "take place", "take pride in",
    "take steps", "take the place of", "take turns", "take up",
    "take up with", "talk about", "talk into", "talk out",
    "talk over", "taste of", "tear down", "tear up",
    "tell apart", "tell from", "tend to", "testify to",
    "thank for", "think about", "think of", "think over",
    "think through", "thousands of", "throw away", "throw light on",
    "throw up", "tie up", "tip over", "tire of", "to and fro",
    "to some extent", "to the point", "toe the line", "together with",
    "top off", "touch on", "touch up", "track down",
    "transform into", "treat as", "triumph over", "try on",
    "try one's best", "try out", "tune in", "turn aside",
    "turn away", "turn back", "turn down", "turn in", "turn into",
    "turn off", "turn on", "turn one's back on", "turn out",
    "turn over", "turn to", "turn up", "tutor in",
    # U
    "under control", "under the circumstances", "under way",
    "up to", "up to date", "urge on", "use up", "used to",
    "used to do",
    # V
    "value at", "vary from", "vary with", "venture into",
    "vote for", "vote on",
    # W
    "wait for", "wait on", "wake up", "warm up", "warn against",
    "warn of", "wash up", "watch for", "watch out for",
    "wave aside", "wear away", "wear off", "wear out",
    "what about", "what if", "whether or not", "wind up",
    "wipe out", "wish for", "with regard to", "with the exception of",
    "withdraw from", "without question", "wonder at", "word for word",
    "work at", "work on", "work out", "worry about",
    "worse still", "worth of", "worthy of", "wrap up",
    "write down", "write off",
    # Y
    "year after year", "year by year",
    # Z
    "zone off",
}

def check_phrase(words, phrases=None):
    """
    检测文本中是否包含已知短语。
    words: 分词后的单词列表 (list of str)
    phrases: 可选的短语集合（默认使用 CET6_PHRASES）
    returns: (匹配的短语, 匹配的单词数) 或 (None, 0)
    """
    if phrases is None:
        phrases = CET6_PHRASES

    text_lower = ' '.join(w.lower() for w in words)

    # 按短语长度降序排序，优先匹配长短语
    sorted_phrases = sorted(phrases, key=lambda x: -len(x.split()))

    for phrase in sorted_phrases:
        if phrase in text_lower:
            word_count = len(phrase.split())
            return phrase, word_count

    return None, 0
